# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, '8.1'
use_frameworks!

target 'Trip-Planner' do

pod 'GoogleMaps'

end

target 'Trip-PlannerTests' do

end

target 'Trip-PlannerUITests' do

end

